### ISSUE TITLE
slider position broken when dragging if scroll pane is not the same height as content

### ISSUE THREAD

**Issue by flexphperia** [jamesflorentino/nanoScrollerJS#244] opened 2014-06-27 19:02 UTC
When in CSS I've added ``` top ``` and  ```bottom ``` values into ``` .nano-pane ``` class to create scrollbar lower than content height then clicking and draging slider are broken.

Here's demo:
http://jsfiddle.net/eR34B/

**Comment by erikhagreis** [comment] 2015-04-09 21:41
Hi, I just dove into the code as I wanted to achieve the same effect. I made a small change in the javascript code, the reset function line line 719.

before:
`sliderHeight = Math.round(paneOuterHeight / contentHeight * paneOuterHeight);`

after:
`sliderHeight = Math.round(paneOuterHeight / contentHeight * paneHeight);`

Basically `paneOuterHeight` means visible height of the scrollWindow. `paneHeight` is the height of the scrollTrack. I used the idea that the ratio `windowHeight / contentHeight` should equal `sliderHeight / trackHeight`. 

At first glance this simple change did the trick. Can you verify?

**Comment by kristerkari** [comment] 2015-04-10 07:52
@erikhagreis Thanks for helping out!

I tried to reproduce the problem with the JSFiddle from @flexphperia and nanoScroller 0.8.5, but it seemed to work just fine for me: https://jsfiddle.net/eR34B/3/

Is there something still broken with the scrolling/dragging? If there is, could you provide a demo of the broken functionality?

**Comment by erikhagreis** [comment] 2015-04-10 08:40
Yeah the issue only becomes apparent in some cases, where the contentHeight is only slightly greater than the trackHeight. I'll try to create a fiddle that demonstrates this.

**Comment by kristerkari** [comment] 2015-04-10 08:41
@erikhagreis Thanks, that'd be great

**Comment by erikhagreis** [comment] 2015-04-10 08:57
This fiddle shows the error: https://jsfiddle.net/pgzeLxre/2/
In this fiddle the error seems fixed: https://jsfiddle.net/pgzeLxre/3/

**Comment by kristerkari** [comment] 2015-04-10 09:03
Alright, looks like the fix works. I'll need to run the demo / your code in different browsers to see that it does not break anything else. :+1:

**Comment by erikhagreis** [comment] 2015-04-10 09:09
thanks for checking :)

**Comment by kristerkari** [comment] 2015-04-11 19:31
Should be fixed with release 0.8.6. Let's reopen if that is not the case.

**Closed by kristerkari** 2015-04-11 19:31 UTC
Labels: Bug, Help needed
