### ISSUE TITLE
[BUG] crashes with bootstrap dropdown-menu

### ISSUE THREAD

**Issue by neuropass** [jamesflorentino/nanoScrollerJS#309] opened 2015-07-07 22:41 UTC
For whatever reason it does not get initialized when used withing the bootstrap dropdown.

Could you please investigate on the cause? Such a pity. I think the dropdown would be the number 1 spot where you use the nanoscroller.

Thanks!

**Comment by MaksJS** [comment] 2015-08-17 14:45
same prob here

**Comment by SiteSplat** [comment] 2016-12-13 17:38
It has nothing to do with nanoscroller. The reason is that the dropdown is already hidden on page load therefore nano is not initialized. You need to initialize it when you click on the dropdown...

**Comment by kristerkari** [comment] 2017-06-28 21:42
I'll close this as it is not a bug in nanoscroller

**Closed by kristerkari** 2017-06-28 21:42 UTC
